### ISSUE TITLE
Failed to parse [querydetails]

### ISSUE THREAD

**Issue by zmallen** [zmallen/robin#4]
Branch is feature-pdnsRecursor.

When upgrading to latest pdns recursor, elasticsearch throws the following error on a log message with 'querydetails' in the field (a sinkhole):

logstash_1      | {
logstash_1      |          "message" => "<134>Sep  5 01:40:57 0e0ef9845f53 pdns_recursor[14]: 4 {\"id\":\"id:2000 SINKHOLE\",\"app\":\"pdns_recursor\",\"querydetails\":{\"localaddr\":\"0.0.0.0\",\"querytype\":\"A\",\"thedomain\":\"www.bad.com.\",\"requestingip\":\"192.168.99.1\"}}",
logstash_1      |         "@version" => "1",
logstash_1      |       "@timestamp" => "2015-09-05T01:40:57.947Z",
logstash_1      |             "host" => [
logstash_1      |         [0] "172.17.0.19",
logstash_1      |         [1] "0e0ef9845f53"
logstash_1      |     ],
logstash_1      |            "evtid" => "134",
logstash_1      |             "date" => "Sep  5 01:40:57",
logstash_1      |             "prog" => "pdns_recursor[14]",
logstash_1      |          "program" => "pdns_recursor",
logstash_1      |              "pid" => "14",
logstash_1      |           "return" => "4",
logstash_1      |      "jsonpayload" => "{\"id\":\"id:2000 SINKHOLE\",\"app\":\"pdns_recursor\",\"querydetails\":{\"localaddr\":\"0.0.0.0\",\"querytype\":\"A\",\"thedomain\":\"www.bad.com.\",\"requestingip\":\"192.168.99.1\"}}",
logstash_1      |               "id" => "id:2000 SINKHOLE",
logstash_1      |              "app" => "pdns_recursor",
logstash_1      |     "querydetails" => {
logstash_1      |            "localaddr" => "0.0.0.0",
logstash_1      |            "querytype" => "A",
logstash_1      |            "thedomain" => "www.bad.com.",
logstash_1      |         "requestingip" => "192.168.99.1"
logstash_1      |     }
logstash_1      | }
elasticsearch_1 | [2015-09-05 01:40:58,772][DEBUG][action.bulk              ] [Meteorite II] [logstash-2015.09.05][3] failed to execute bulk item (index) index {[logstash-2015.09.05][logs][AU-bKecSm9u8cRQFeJ94], source[{"message":"<134>Sep  5 01:40:57 0e0ef9845f53 pdns_recursor[14]: 4 {\"id\":\"id:2000 SINKHOLE\",\"app\":\"pdns_recursor\",\"querydetails\":{\"localaddr\":\"0.0.0.0\",\"querytype\":\"A\",\"thedomain\":\"www.bad.com.\",\"requestingip\":\"192.168.99.1\"}}","@version":"1","@timestamp":"2015-09-05T01:40:57.947Z","host":["172.17.0.19","0e0ef9845f53"],"evtid":"134","date":"Sep  5 01:40:57","prog":"pdns_recursor[14]","program":"pdns_recursor","pid":"14","return":"4","jsonpayload":"{\"id\":\"id:2000 SINKHOLE\",\"app\":\"pdns_recursor\",\"querydetails\":{\"localaddr\":\"0.0.0.0\",\"querytype\":\"A\",\"thedomain\":\"www.bad.com.\",\"requestingip\":\"192.168.99.1\"}}","id":"id:2000 SINKHOLE","app":"pdns_recursor","querydetails":{"localaddr":"0.0.0.0","querytype":"A","thedomain":"www.bad.com.","requestingip":"192.168.99.1"}}]}
elasticsearch_1 | org.elasticsearch.index.mapper.MapperParsingException: failed to parse [querydetails]
elasticsearch_1 |   at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:411)
elasticsearch_1 |   at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:554)
elasticsearch_1 |   at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:487)
elasticsearch_1 |   at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:544)
elasticsearch_1 |   at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:493)
elasticsearch_1 |   at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:466)
elasticsearch_1 |   at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:418)
elasticsearch_1 |   at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:148)
elasticsearch_1 |   at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase.performOnPrimary(TransportShardReplicationOperationAction.java:574)
elasticsearch_1 |   at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1.doRun(TransportShardReplicationOperationAction.java:440)
elasticsearch_1 |   at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
elasticsearch_1 |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
elasticsearch_1 |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
elasticsearch_1 |   at java.lang.Thread.run(Thread.java:745)
elasticsearch_1 | Caused by: org.elasticsearch.ElasticsearchIllegalArgumentException: unknown property [localaddr]
elasticsearch_1 |   at org.elasticsearch.index.mapper.core.StringFieldMapper.parseCreateFieldForString(StringFieldMapper.java:331)
elasticsearch_1 |   at org.elasticsearch.index.mapper.core.StringFieldMapper.parseCreateField(StringFieldMapper.java:277)
elasticsearch_1 |   at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:401)
elasticsearch_1 |   ... 13 more

**Comment by zmallen** [comment]
@ccmolik

**Comment by zmallen** [comment]
to recreate:
1) Pull newest branch

2) `docker-compose build && docker-compose up`

3) Connect to redis via redis-cli, type: `set "A:www.bad.com." "1.2.3.4"`

4) dig @robinip www.bad.com

5) view logs

**Comment by ccmolik** [comment]
Cannot repro here. 

```
robin_1         | Sep 10 02:49:41 PowerDNS Recursor 3.7.3 (jenkins@autotest.powerdns.com) (C) 2001-2015 PowerDNS.COM BV
robin_1         | Sep 10 02:49:41 Using 64-bits mode. Built on 20150609121259 by root@autotest.powerdns.com, gcc 4.7.2.
robin_1         | Sep 10 02:49:41 PowerDNS comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it according to the terms of the GPL version 2.
robin_1         | Sep 10 02:49:41 Reading random entropy from '/dev/urandom'
robin_1         | Sep 10 02:49:41 Only allowing queries from: 127.0.0.0/8, 10.0.0.0/8
robin_1         | Sep 10 02:49:41 Will not send queries to: 127.0.0.0/8, 10.0.0.0/8, 100.64.0.0/10, 169.254.0.0/16, 192.168.0.0/16, 172.16.0.0/12, ::1/128, fc00::/7, fe80::/10, 0.0.0.0/8, 192.0.0.0/24, 192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24, 240.0.0.0/4, ::/96, ::ffff:0:0/96, 100::/64, 2001:db8::/32, 0.0.0.0, ::
robin_1         | Sep 10 02:49:41 PowerDNS Recursor itself will distribute queries over threads
robin_1         | Sep 10 02:49:41 If using IPv6, please raise sysctl net.ipv6.route.max_size, currently set to 4096 which is < 16384
robin_1         | Sep 10 02:49:41 NOT using IPv6 for outgoing queries - set 'query-local-address6=::' to enable
robin_1         | Sep 10 02:49:41 Inserting rfc 1918 private space zones
robin_1         | Sep 10 02:49:41 Listening for UDP queries on 0.0.0.0:53
robin_1         | Sep 10 02:49:41 Enabled TCP data-ready filter for (slight) DoS protection
robin_1         | Sep 10 02:49:41 Listening for TCP queries on 0.0.0.0:53
robin_1         | Sep 10 02:49:41 Launching 9 threads
robin_1         | Sep 10 02:49:41 Done priming cache with root hints
robin_1         | Sep 10 02:49:41 Done priming cache with root hints
robin_1         | Sep 10 02:49:41 Done priming cache with root hints
robin_1         | Sep 10 02:49:41 Done priming cache with root hints
robin_1         | Sep 10 02:49:41 Done priming cache with root hints
robin_1         | Sep 10 02:49:41 Done priming cache with root hints
robin_1         | Sep 10 02:49:41 Done priming cache with root hints
robin_1         | Sep 10 02:49:41 Done priming cache with root hints
robin_1         | Sep 10 02:49:41 Done priming cache with root hints
robin_1         | Sep 10 02:49:41 6 {"id":"id:1000 STARTUP","app":"pdns_recursor","querydetails":"redis"}
robin_1         | Sep 10 02:49:41 Loaded 'lua' script from '/etc/powerdns/sinkhole.lua'
robin_1         | Sep 10 02:49:41 6 {"id":"id:1000 STARTUP","app":"pdns_recursor","querydetails":"redis"}
robin_1         | Sep 10 02:49:41 6 {"id":"id:1000 STARTUP","app":"pdns_recursor","querydetails":"redis"}
robin_1         | Sep 10 02:49:41 Loaded 'lua' script from '/etc/powerdns/sinkhole.lua'
robin_1         | Sep 10 02:49:41 Loaded 'lua' script from '/etc/powerdns/sinkhole.lua'
robin_1         | Sep 10 02:49:41 6 {"id":"id:1000 STARTUP","app":"pdns_recursor","querydetails":"redis"}
robin_1         | Sep 10 02:49:41 Loaded 'lua' script from '/etc/powerdns/sinkhole.lua'
robin_1         | Sep 10 02:49:41 6 {"id":"id:1000 STARTUP","app":"pdns_recursor","querydetails":"redis"}
robin_1         | Sep 10 02:49:41 Loaded 'lua' script from '/etc/powerdns/sinkhole.lua'
robin_1         | Sep 10 02:49:41 6 {"id":"id:1000 STARTUP","app":"pdns_recursor","querydetails":"redis"}
robin_1         | Sep 10 02:49:41 6 {"id":"id:1000 STARTUP","app":"pdns_recursor","querydetails":"redis"}
robin_1         | Sep 10 02:49:41 Loaded 'lua' script from '/etc/powerdns/sinkhole.lua'
robin_1         | Sep 10 02:49:41 6 {"id":"id:1000 STARTUP","app":"pdns_recursor","querydetails":"redis"}
robin_1         | Sep 10 02:49:41 Loaded 'lua' script from '/etc/powerdns/sinkhole.lua'
robin_1         | Sep 10 02:49:41 Loaded 'lua' script from '/etc/powerdns/sinkhole.lua'
robin_1         | Sep 10 02:49:41 Enabled 'epoll' multiplexer
robin_1         | Sep 10 02:49:41 6 {"id":"id:1000 STARTUP","app":"pdns_recursor","querydetails":"redis"}
robin_1         | Sep 10 02:49:41 Loaded 'lua' script from '/etc/powerdns/sinkhole.lua'
robin_1         | Sep 10 02:49:41 Refreshed . records
robin_1         | Sep 10 02:49:41 Refreshed . records
robin_1         | Sep 10 02:49:41 Refreshed . records
robin_1         | Sep 10 02:49:41 Refreshed . records
robin_1         | Sep 10 02:49:42 Refreshed . records
robin_1         | Sep 10 02:49:42 Refreshed . records
robin_1         | Sep 10 02:49:42 Refreshed . records
robin_1         | Sep 10 02:49:42 Refreshed . records
robin_1         | Sep 10 02:49:42 Refreshed . records
logstash_1      | Sep 10, 2015 2:49:46 AM org.elasticsearch.node.internal.InternalNode <init>
logstash_1      | INFO: [logstash-373406e30c93-1-11628] version[1.7.0], pid[1], build[929b973/2015-07-16T14:31:07Z]
logstash_1      | Sep 10, 2015 2:49:46 AM org.elasticsearch.node.internal.InternalNode <init>
logstash_1      | INFO: [logstash-373406e30c93-1-11628] initializing ...
logstash_1      | Sep 10, 2015 2:49:46 AM org.elasticsearch.plugins.PluginsService <init>
logstash_1      | INFO: [logstash-373406e30c93-1-11628] loaded [], sites []
elasticsearch_1 | [2015-09-10 02:49:46,821][DEBUG][action.admin.cluster.health] [Prototype] observer: timeout notification from cluster service. timeout setting [5s], time since start [5s]
kibana_1        | {"name":"Kibana","hostname":"625745af1633","pid":6,"level":30,"msg":"No existing kibana index found","time":"2015-09-10T02:49:46.825Z","v":0}
kibana_1        | {"name":"Kibana","hostname":"625745af1633","pid":6,"level":30,"msg":"Listening on 0.0.0.0:5601","time":"2015-09-10T02:49:46.841Z","v":0}
logstash_1      | Sep 10, 2015 2:49:47 AM org.elasticsearch.bootstrap.Natives <clinit>
logstash_1      | WARNING: JNA not found. native methods will be disabled.
logstash_1      | Sep 10, 2015 2:49:48 AM org.elasticsearch.node.internal.InternalNode <init>
logstash_1      | INFO: [logstash-373406e30c93-1-11628] initialized
logstash_1      | Sep 10, 2015 2:49:48 AM org.elasticsearch.node.internal.InternalNode start
logstash_1      | INFO: [logstash-373406e30c93-1-11628] starting ...
logstash_1      | Sep 10, 2015 2:49:48 AM org.elasticsearch.transport.TransportService doStart
logstash_1      | INFO: [logstash-373406e30c93-1-11628] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/172.17.0.6:9300]}
logstash_1      | Sep 10, 2015 2:49:48 AM org.elasticsearch.discovery.DiscoveryService doStart
logstash_1      | INFO: [logstash-373406e30c93-1-11628] elasticsearch/IQR0Xo5mTMiDcoV6Y3wX5A
elasticsearch_1 | [2015-09-10 02:49:51,494][INFO ][cluster.service          ] [Prototype] added {[logstash-373406e30c93-1-11628][IQR0Xo5mTMiDcoV6Y3wX5A][373406e30c93][inet[/172.17.0.6:9300]]{data=false, client=true},}, reason: zen-disco-receive(join from node[[logstash-373406e30c93-1-11628][IQR0Xo5mTMiDcoV6Y3wX5A][373406e30c93][inet[/172.17.0.6:9300]]{data=false, client=true}])
logstash_1      | Sep 10, 2015 2:49:51 AM org.elasticsearch.cluster.service.InternalClusterService$UpdateTask run
logstash_1      | INFO: [logstash-373406e30c93-1-11628] detected_master [Prototype][aBQYPaPyRPm-5-XJrXfxPw][d6b726ab821f][inet[/172.17.0.4:9300]], added {[Prototype][aBQYPaPyRPm-5-XJrXfxPw][d6b726ab821f][inet[/172.17.0.4:9300]],}, reason: zen-disco-receive(from master [[Prototype][aBQYPaPyRPm-5-XJrXfxPw][d6b726ab821f][inet[/172.17.0.4:9300]]])
logstash_1      | Sep 10, 2015 2:49:51 AM org.elasticsearch.node.internal.InternalNode start
logstash_1      | INFO: [logstash-373406e30c93-1-11628] started
elasticsearch_1 | [2015-09-10 02:50:00,736][INFO ][cluster.metadata         ] [Prototype] [.marvel-2015.09.10] update_mapping [node_event] (dynamic)
robin_1         | Sep 10 02:51:15 6 {"id":"id:1001 QUERY","app":"pdns_recursor","querydetails":{"localaddr":"0.0.0.0","querytype":"A","thedomain":"www.google.com.","requestingip":"10.40.0.118"}}
elasticsearch_1 | [2015-09-10 02:51:15,269][INFO ][cluster.metadata         ] [Prototype] [logstash-2015.09.10] creating index, cause [auto(bulk api)], templates [logstash], shards [5]/[1], mappings [_default_, logs]
logstash_1      | {
logstash_1      |          "message" => "<134>Sep 10 02:51:15 d4d1750c1c4b pdns_recursor[15]: 6 {\"id\":\"id:1001 QUERY\",\"app\":\"pdns_recursor\",\"querydetails\":{\"localaddr\":\"0.0.0.0\",\"querytype\":\"A\",\"thedomain\":\"www.google.com.\",\"requestingip\":\"10.40.0.118\"}}",
logstash_1      |         "@version" => "1",
logstash_1      |       "@timestamp" => "2015-09-10T02:51:15.208Z",
logstash_1      |             "host" => [
logstash_1      |         [0] "172.17.0.8",
logstash_1      |         [1] "d4d1750c1c4b"
logstash_1      |     ],
logstash_1      |            "evtid" => "134",
logstash_1      |             "date" => "Sep 10 02:51:15",
logstash_1      |             "prog" => "pdns_recursor[15]",
logstash_1      |          "program" => "pdns_recursor",
logstash_1      |              "pid" => "15",
logstash_1      |           "return" => "6",
logstash_1      |      "jsonpayload" => "{\"id\":\"id:1001 QUERY\",\"app\":\"pdns_recursor\",\"querydetails\":{\"localaddr\":\"0.0.0.0\",\"querytype\":\"A\",\"thedomain\":\"www.google.com.\",\"requestingip\":\"10.40.0.118\"}}",
logstash_1      |               "id" => "id:1001 QUERY",
logstash_1      |              "app" => "pdns_recursor",
logstash_1      |     "querydetails" => {
logstash_1      |            "localaddr" => "0.0.0.0",
logstash_1      |            "querytype" => "A",
logstash_1      |            "thedomain" => "www.google.com.",
logstash_1      |         "requestingip" => "10.40.0.118"
logstash_1      |     }
logstash_1      | }
elasticsearch_1 | [2015-09-10 02:51:15,417][INFO ][cluster.metadata         ] [Prototype] [logstash-2015.09.10] update_mapping [logs] (dynamic)
elasticsearch_1 | [2015-09-10 02:51:21,122][INFO ][cluster.metadata         ] [Prototype] [.marvel-2015.09.10] update_mapping [index_event] (dynamic)
robin_1         | Sep 10 02:51:28 6 {"id":"id:1001 QUERY","app":"pdns_recursor","querydetails":{"localaddr":"0.0.0.0","querytype":"A","thedomain":"www.bad.com.","requestingip":"10.40.0.118"}}
robin_1         | Sep 10 02:51:28 4 {"id":"id:2000 SINKHOLE","app":"pdns_recursor","querydetails":{"localaddr":"0.0.0.0","querytype":"A","thedomain":"www.bad.com.","requestingip":"10.40.0.118"}}
logstash_1      | {
logstash_1      |          "message" => "<134>Sep 10 02:51:28 d4d1750c1c4b pdns_recursor[15]: 6 {\"id\":\"id:1001 QUERY\",\"app\":\"pdns_recursor\",\"querydetails\":{\"localaddr\":\"0.0.0.0\",\"querytype\":\"A\",\"thedomain\":\"www.bad.com.\",\"requestingip\":\"10.40.0.118\"}}",
logstash_1      |         "@version" => "1",
logstash_1      |       "@timestamp" => "2015-09-10T02:51:28.444Z",
logstash_1      |             "host" => [
logstash_1      |         [0] "172.17.0.8",
logstash_1      |         [1] "d4d1750c1c4b"
logstash_1      |     ],
logstash_1      |            "evtid" => "134",
logstash_1      |             "date" => "Sep 10 02:51:28",
logstash_1      |             "prog" => "pdns_recursor[15]",
logstash_1      |          "program" => "pdns_recursor",
logstash_1      |              "pid" => "15",
logstash_1      |           "return" => "6",
logstash_1      |      "jsonpayload" => "{\"id\":\"id:1001 QUERY\",\"app\":\"pdns_recursor\",\"querydetails\":{\"localaddr\":\"0.0.0.0\",\"querytype\":\"A\",\"thedomain\":\"www.bad.com.\",\"requestingip\":\"10.40.0.118\"}}",
logstash_1      |               "id" => "id:1001 QUERY",
logstash_1      |              "app" => "pdns_recursor",
logstash_1      |     "querydetails" => {
logstash_1      |            "localaddr" => "0.0.0.0",
logstash_1      |            "querytype" => "A",
logstash_1      |            "thedomain" => "www.bad.com.",
logstash_1      |         "requestingip" => "10.40.0.118"
logstash_1      |     }
logstash_1      | }
logstash_1      | {
logstash_1      |          "message" => "<134>Sep 10 02:51:28 d4d1750c1c4b pdns_recursor[15]: 4 {\"id\":\"id:2000 SINKHOLE\",\"app\":\"pdns_recursor\",\"querydetails\":{\"localaddr\":\"0.0.0.0\",\"querytype\":\"A\",\"thedomain\":\"www.bad.com.\",\"requestingip\":\"10.40.0.118\"}}",
logstash_1      |         "@version" => "1",
logstash_1      |       "@timestamp" => "2015-09-10T02:51:28.445Z",
logstash_1      |             "host" => [
logstash_1      |         [0] "172.17.0.8",
logstash_1      |         [1] "d4d1750c1c4b"
logstash_1      |     ],
logstash_1      |            "evtid" => "134",
logstash_1      |             "date" => "Sep 10 02:51:28",
logstash_1      |             "prog" => "pdns_recursor[15]",
logstash_1      |          "program" => "pdns_recursor",
logstash_1      |              "pid" => "15",
logstash_1      |           "return" => "4",
logstash_1      |      "jsonpayload" => "{\"id\":\"id:2000 SINKHOLE\",\"app\":\"pdns_recursor\",\"querydetails\":{\"localaddr\":\"0.0.0.0\",\"querytype\":\"A\",\"thedomain\":\"www.bad.com.\",\"requestingip\":\"10.40.0.118\"}}",
logstash_1      |               "id" => "id:2000 SINKHOLE",
logstash_1      |              "app" => "pdns_recursor",
logstash_1      |     "querydetails" => {
logstash_1      |            "localaddr" => "0.0.0.0",
logstash_1      |            "querytype" => "A",
logstash_1      |            "thedomain" => "www.bad.com.",
logstash_1      |         "requestingip" => "10.40.0.118"
logstash_1      |     }
logstash_1      | }

```

**Comment by ccmolik** [comment]
Have you tried the following?

```
$ sudo docker rm -v $(sudo docker ps -aq)
$ sudo docker rmi $(sudo docker images -aq)
$ sudo docker-compose build
$ sudo docker-compose up
```

It's possible you're getting bitten by a bad cache or something.

**Comment by zmallen** [comment]
@ccmolik thanks, gotta check this out now..
